//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.removeShaped(<openmodularturrets:rocket_turret>, [[<mekanism:ingot:3>, <openmodularturrets:intermediate_tiered:13>, <mekanism:ingot:3>],[<mekanism:ingot:3>, <openmodularturrets:intermediate_tiered:8>, <mekanism:ingot:3>], [<minecraft:diamond>, <openmodularturrets:intermediate_regular>, <minecraft:diamond>]]);
recipes.removeShaped(<hbm:weapon_pipe_rusty>, [[<ore:ingotIron>, <minecraft:iron_ingot>, null],[null, <minecraft:iron_ingot>, null], [null, <minecraft:iron_ingot>, null]]);
recipes.removeShaped(<hbm:weapon_golf_club>, [[<ore:ingotSteel>, <hbm:plate_steel>, null],[null, <hbm:plate_steel>, null], [null, <hbm:plate_steel>, null]]);
recipes.removeShaped(<hbm:meteorite_sword>, [[null, null, <hbm:blade_meteorite>],[<hbm:plate_gold>, <hbm:blade_meteorite>, null], [<minecraft:stick>, <hbm:plate_gold>, null]]);
furnace.remove(<variedcommodities:ingot_steel>, <minecraft:iron_ingot>);
recipes.removeShaped(<mysticalworld:copper_sword>, [[null, <ore:ingotCopper>, null],[null, <ore:ingotCopper>, null], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<mysticalworld:copper_shovel>, [[null, <ore:ingotCopper>, null],[null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<mysticalworld:copper_pickaxe>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>],[null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<mysticalworld:copper_hoe>, [[null, <ore:ingotCopper>, <ore:ingotCopper>],[null, <ore:stickWood>, null], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<mysticalworld:copper_axe>, [[null, <ore:ingotCopper>, <ore:ingotCopper>],[null, <ore:stickWood>, <ore:ingotCopper>], [null, <ore:stickWood>, null]]);
recipes.removeShaped(<mysticalworld:copper_knife>, [[null, null, <ore:ingotCopper>],[null, <ore:ingotCopper>, null], [<ore:stickWood>, null, null]]);
recipes.removeShaped(<mysticalworld:copper_boots>, [[null, null, null],[<ore:ingotCopper>, null, <ore:ingotCopper>], [<ore:ingotCopper>, null, <ore:ingotCopper>]]);
recipes.removeShaped(<mysticalworld:copper_leggings>, [[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>],[<ore:ingotCopper>, null, <ore:ingotCopper>], [<ore:ingotCopper>, null, <ore:ingotCopper>]]);
recipes.removeShaped(<mysticalworld:copper_helmet>, [[null, null, null],[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, null, <ore:ingotCopper>]]);
recipes.removeShaped(<mysticalworld:copper_chestplate>, [[<ore:ingotCopper>, null, <ore:ingotCopper>],[<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>], [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]]);
recipes.removeShaped(<notreepunching:shovel/flint>, [[null, <notreepunching:flint_shard>, <notreepunching:flint_shard>],[null, <ore:string>, <notreepunching:flint_shard>], [<minecraft:stick>, null, null]]);
//Don't touch me!
//#Add
recipes.addShaped(<minecraft:string> * 4, [[null, null, null],[null, null, <minecraft:wool:*>], [null, null, null]]);
recipes.addShapeless(<minecraft:string> * 4, [<minecraft:wool>]);
recipes.addShaped(<mekanism:ingot:4>, [[null, null, null],[null, <hbm:ingot_steel>, null], [null, null, null]]);
recipes.addShaped(<hbm:ingot_steel>, [[null, null, null],[null, <mekanism:ingot:4>, null], [null, null, null]]);
recipes.addShapeless(<minecraft:bone> * 2, [<minecraft:iron_ingot>,<hbm:fluorite>]);
furnace.addRecipe(<hbm:block_copper>, <levviatasores:raw_copper_block>, 0.0);
recipes.addShaped(<minecraft:ender_pearl>, [[<minecraft:end_stone>, <minecraft:gold_ingot>, <minecraft:end_stone>],[<minecraft:dye:5>, <minecraft:end_stone>, <minecraft:dye:5>], [<minecraft:end_stone>, <minecraft:gold_ingot>, <minecraft:end_stone>]]);
recipes.addShaped(<minecraft:end_stone>, [[null, <minecraft:dye:5>, null],[<minecraft:dye:5>, <minecraft:cobblestone>, <minecraft:dye:5>], [null, <minecraft:dye:5>, null]]);
furnace.addRecipe(<levviatasores:copper_ingot>, <levviatasores:raw_copper>, 0.0);
recipes.addShaped(<openmodularturrets:rocket_turret>, [[<mekanism:ingot:3>, <openmodularturrets:intermediate_tiered:13>, <mekanism:ingot:3>],[<mekanism:ingot:3>, <openmodularturrets:intermediate_tiered:8>, <mekanism:ingot:3>], [<hbm:ingot_advanced_alloy>, <openmodularturrets:intermediate_regular>, <hbm:ingot_advanced_alloy>]]);
recipes.addShapeless(<hbm:ball_fireclay> * 4, [<minecraft:clay_ball>,<minecraft:clay_ball>,<minecraft:clay_ball>,<hbm:ingot_aluminium>]);
recipes.addShapeless(<minecraft:leather> * 2, [<minecraft:saddle>]);
recipes.addShapeless(<minecraft:wool> * 2, [<minecraft:bed:*>]);
recipes.addShaped(<minecraft:flint>, [[null, null, null],[null, <notreepunching:flint_shard>, <notreepunching:flint_shard>], [null, <notreepunching:flint_shard>, <notreepunching:flint_shard>]]);
recipes.addShapeless(<minecraft:flint>, [<minecraft:diamond_shovel>.anyDamage(),<minecraft:gravel>]);
recipes.addShaped(<minecraft:flint>, [[null, null, null],[<notreepunching:axe/flint:8>.anyDamage(), <minecraft:flint>, null], [null, null, null]]);
recipes.addShaped(<notreepunching:shovel/flint>, [[null, <notreepunching:flint_shard>, null],[null, <ore:string>, null], [null, <minecraft:stick>, null]]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:black_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:red_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:green_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:brown_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:blue_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:purple_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:cyan_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:silver_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:gray_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:pink_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:lime_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:yellow_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:light_blue_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:magenta_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:orange_shulker_box>]);
recipes.addShapeless(<minecraft:shulker_shell>, [<minecraft:white_shulker_box>]);
recipes.addShapeless(<minecraft:iron_ingot> * 3, [<minecraft:cauldron>]);
recipes.addShapeless(<minecraft:iron_ingot>, [<minecraft:shears>]);
recipes.addShapeless(<minecraft:chest>, [<minecraft:chest_minecart>]);
recipes.addShapeless(<minecraft:tnt>, [<minecraft:tnt_minecart>]);
recipes.addShapeless(<minecraft:gunpowder> * 5, [<minecraft:tnt>]);
recipes.addShapeless(<minecraft:flint>, [<minecraft:flint_and_steel>]);
recipes.addShapeless(<minecraft:leather>, [<minecraft:leather_boots>]);
recipes.addShapeless(<minecraft:leather> * 2, [<minecraft:leather_leggings>]);
recipes.addShapeless(<minecraft:leather> * 3, [<minecraft:leather_chestplate>]);
recipes.addShapeless(<minecraft:leather>, [<minecraft:leather_helmet>]);
recipes.addShapeless(<minecraft:leather>, [<minecraft:item_frame>]);
recipes.addShapeless(<minecraft:ender_eye>, [<minecraft:ender_chest>]);
recipes.addShapeless(<minecraft:bow>, [<minecraft:dispenser>]);
recipes.addShapeless(<minecraft:gold_ingot>, [<minecraft:light_weighted_pressure_plate>]);
recipes.addShapeless(<minecraft:book>, [<securitycraft:reinforced_bookshelf>]);
recipes.addShapeless(<minecraft:book>, [<quark:custom_bookshelf:4>]);
recipes.addShapeless(<minecraft:book>, [<quark:custom_bookshelf:3>]);
recipes.addShapeless(<minecraft:book>, [<quark:custom_bookshelf:2>]);
recipes.addShapeless(<minecraft:book>, [<quark:custom_bookshelf:1>]);
recipes.addShapeless(<minecraft:book>, [<quark:custom_bookshelf>]);
recipes.addShapeless(<minecraft:book>, [<minecraft:bookshelf>]);
recipes.addShapeless(<minecraft:planks> * 8, [<minecraft:chest>]);
furnace.addRecipe(<minecraft:diamond> * 3, <minecraft:diamond_horse_armor>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 2, <minecraft:compass>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:lava_bucket>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:water_bucket>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:milk_bucket>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:bucket>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:chainmail_boots>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 2, <minecraft:chainmail_leggings>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 2, <minecraft:chainmail_chestplate>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:chainmail_helmet>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:saddle>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 9, <minecraft:anvil:2>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 9, <minecraft:anvil:1>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 9, <minecraft:anvil>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:piston>, 0.0);
furnace.addRecipe(<minecraft:diamond>, <minecraft:enchanting_table>, 0.0);
furnace.addRecipe(<minecraft:obsidian> * 3, <hbm:cladding_obsidian>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:cladding_iron>, 0.0);
furnace.addRecipe(<hbm:ingot_electronium> * 2, <hbm:cladding_electronium>, 0.0);
furnace.addRecipe(<hbm:ingot_dineutronium> * 2, <hbm:cladding_di>, 0.0);
furnace.addRecipe(<hbm:ingot_euphemium>, <hbm:cladding_euphemium>, 0.0);
furnace.addRecipe(<hbm:ingot_gh336> * 2, <hbm:cladding_ghiorsium>, 0.0);
furnace.addRecipe(<hbm:plate_paa> * 2, <hbm:cladding_paa>, 0.0);
furnace.addRecipe(<hbm:ingot_desh> * 2, <hbm:cladding_desh>, 0.0);
furnace.addRecipe(<hbm:ingot_lead> * 2, <hbm:cladding_lead>, 0.0);
furnace.addRecipe(<levviatasores:copper_ingot> * 2, <hbm:pads_static>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <hbm:attachment_mask_mono>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <hbm:attachment_mask_mono>, 0.0);
furnace.addRecipe(<hbm:ingot_meteorite_forged>, <hbm:gas_mask_filter_radon>, 0.0);
furnace.addRecipe(<hbm:ingot_zirconium> * 2, <hbm:gas_mask_filter_combo>, 0.0);
furnace.addRecipe(<minecraft:iron_nugget> * 7, <hbm:gas_mask_filter>, 0.0);
furnace.addRecipe(<minecraft:iron_nugget> * 2, <hbm:gas_mask_filter>, 0.0);
furnace.addRecipe(<hbm:billet_zirconium>, <hbm:gas_mask_filter_mono>, 0.0);
furnace.addRecipe(<minecraft:iron_nugget> * 7, <hbm:gas_mask_filter_piss>, 0.0);
furnace.addRecipe(<minecraft:iron_nugget> * 7, <hbm:gas_mask_filter_rag>, 0.0);
furnace.addRecipe(<hbm:ingot_steel> * 2, <hbm:cbt_device>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:gun_kit_2>, 0.0);
furnace.addRecipe(<minecraft:iron_nugget> * 7, <hbm:gun_kit_1>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <hbm:syringe_metal_empty>, 0.0);
furnace.addRecipe(<hbm:plate_steel>, <hbm:survey_scanner>, 0.0);
furnace.addRecipe(<hbm:ingot_steel>, <hbm:wiring_red_copper>, 0.0);
furnace.addRecipe(<hbm:ingot_technetium> * 2, <hbm:bismuth_tool>, 0.0);
furnace.addRecipe(<hbm:ingot_tungsten>, <hbm:reacher>, 0.0);
furnace.addRecipe(<hbm:ingot_desh>, <hbm:screwdriver_desh>, 0.0);
furnace.addRecipe(<hbm:ingot_steel>, <hbm:screwdriver>, 0.0);
furnace.addRecipe(<hbm:ingot_aluminium> * 5, <hbm:lung_diagnostic>, 0.0);
furnace.addRecipe(<hbm:plate_desh>, <hbm:digamma_diagnostic>, 0.0);
furnace.addRecipe(<hbm:plate_steel>, <hbm:geiger_counter>, 0.0);
furnace.addRecipe(<hbm:ingot_beryllium>, <hbm:dosimeter>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 2, <hbm:big_sword>, 0.0);
furnace.addRecipe(<minecraft:redstone_block>, <hbm:redstone_sword>, 0.0);
furnace.addRecipe(<hbm:billet_gh336>, <hbm:paa_boots>, 0.0);
furnace.addRecipe(<hbm:billet_gh336>, <hbm:paa_legs>, 0.0);
furnace.addRecipe(<hbm:billet_gh336>, <hbm:paa_plate>, 0.0);
furnace.addRecipe(<hbm:billet_gh336>, <hbm:paa_helmet>, 0.0);
furnace.addRecipe(<hbm:plate_paa>, <hbm:hazmat_paa_boots>, 0.0);
furnace.addRecipe(<hbm:plate_paa>, <hbm:hazmat_paa_helmet>, 0.0);
furnace.addRecipe(<hbm:plate_paa>, <hbm:hazmat_paa_helmet>, 0.0);
furnace.addRecipe(<hbm:plate_paa> * 2, <hbm:hazmat_paa_legs>, 0.0);
furnace.addRecipe(<hbm:plate_paa> * 3, <hbm:hazmat_paa_plate>, 0.0);
furnace.addRecipe(<hbm:plate_paa> * 2, <hbm:hazmat_paa_plate>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:iron_horse_armor>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <minecraft:iron_trapdoor>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <minecraft:iron_door>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_ingot>, <notreepunching:saw/iron>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_nugget> * 2, <locks:iron_lock_pick>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_ingot> * 6, <locks:iron_lock>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_ingot> * 6, <locks:iron_lock>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 2, <locks:iron_lock>, 0.0);
furnace.addRecipe(<minecraft:iron_nugget> * 7, <notreepunching:knife/iron>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_ingot> * 9, <hbm:anvil_iron>, 0.5555555690079927);
furnace.addRecipe(<minecraft:iron_ingot> * 9, <hbm:anvil_iron>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 5, <hbm:gun_deagle>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:gun_revolver_red>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:gun_revolver_silver>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:gun_revolver_blackjack>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:gun_revolver_nopip>, 0.0);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <hbm:gun_revolver_pip>, 0.0);
furnace.addRecipe(<minecraft:diamond>, <notreepunching:saw/diamond>, 0.5555555690079927);
furnace.addRecipe(<minecraft:diamond> * 3, <hbm:diamond_gavel>, 0.5555555690079927);
furnace.addRecipe(<minecraft:diamond>, <minecraft:diamond_boots>, 0.5555555690079927);
furnace.addRecipe(<minecraft:diamond> * 2, <minecraft:diamond_leggings>, 0.5555555690079927);
furnace.addRecipe(<minecraft:diamond> * 3, <minecraft:diamond_chestplate>, 0.5555555690079927);
furnace.addRecipe(<minecraft:diamond>, <minecraft:diamond_helmet>, 0.5555555690079927);
furnace.addRecipe(<minecraft:diamond>, <minecraft:diamond_hoe>, 0.4);
furnace.addRecipe(<minecraft:diamond> * 3, <minecraft:diamond_hoe>, 0.4);
furnace.addRecipe(<minecraft:diamond> * 2, <minecraft:diamond_axe>, 0.4);
furnace.addRecipe(<minecraft:diamond> * 2, <minecraft:diamond_pickaxe>, 0.4);
furnace.addRecipe(<minecraft:diamond>, <minecraft:diamond_sword>, 0.4);
furnace.addRecipe(<minecraft:diamond> * 5, <locks:diamond_lock>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot> * 5, <locks:gold_lock>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot> * 4, <locks:gold_lock>, 0.4);
furnace.addRecipe(<minecraft:gold_nugget> * 7, <notreepunching:knife/gold>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 3, <notreepunching:mattock/gold>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot>, <notreepunching:mattock/gold>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 9, <minecraft:golden_apple:1>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 3, <minecraft:golden_apple>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 3, <hbm:gun_revolver_gold>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 3, <minecraft:golden_horse_armor>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 4, <minecraft:golden_horse_armor>, 0.5555555690079927);
furnace.addRecipe(<minecraft:gold_ingot> * 2, <minecraft:golden_leggings>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot> * 4, <minecraft:golden_leggings>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot> * 3, <minecraft:golden_chestplate>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot>, <minecraft:golden_boots>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot>, <minecraft:golden_helmet>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot> * 3, <minecraft:golden_pickaxe>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot> * 2, <minecraft:golden_axe>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot>, <minecraft:golden_axe>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot>, <minecraft:golden_pickaxe>, 0.4);
furnace.addRecipe(<minecraft:gold_nugget> * 7, <minecraft:golden_shovel>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot>, <notreepunching:saw/gold>, 0.4);
furnace.addRecipe(<minecraft:gold_ingot>, <minecraft:golden_sword>, 0.4);
furnace.addRecipe(<minecraft:gold_nugget> * 7, <notreepunching:saw/gold>, 1.2);
furnace.addRecipe(<minecraft:iron_nugget> * 7, <notreepunching:saw/iron>, 1.2);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <minecraft:iron_horse_armor>, 1.2);
furnace.addRecipe(<minecraft:iron_ingot> * 2, <minecraft:iron_leggings>, 0.8);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:iron_helmet>, 0.4);
furnace.addRecipe(<minecraft:iron_ingot> * 3, <minecraft:iron_boots>, 1.2);
furnace.addRecipe(<minecraft:iron_ingot>, <minecraft:iron_leggings>, 0.4);
//File End
